import os
import re
import json

# Order of lessons
file_order = [
    "Introduzione alle dottrine.html",
    "Tu e la parola di Dio.html",
    "La nuova nascita.html",
    "Ravvedimento dalle Opere Morte.html",
    "Il patto di sangue.html",
    "Imposizione delle mani.html",
    "Resurrezione dei morti.html",
    "Il giudizio eterno.html",
    "Etica Cristiana.html",
    "Relazioni Sane.html",
    "La Chiesa Locale e Struttura Gesù Vive.html"
]

lessons_data = []

# Regex patterns
title_pat = re.compile(r'<title>(.*?)</title>', re.IGNORECASE | re.DOTALL)
h1_pat = re.compile(r'<h1.*?>(.*?)</h1>', re.IGNORECASE | re.DOTALL)
main_pat = re.compile(r'<main.*?>(.*?)</main>', re.IGNORECASE | re.DOTALL)
header_pat = re.compile(r'<header.*?>(.*?)</header>', re.IGNORECASE | re.DOTALL)

for filename in file_order:
    filepath = filename
    if not os.path.exists(filepath):
        print(f"Warning: File {filename} not found.")
        continue
        
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        
    title_match = title_pat.search(content)
    title = title_match.group(1).strip() if title_match else filename.replace(".html", "")
    title = title.replace("Sintesi Dispensa: ", "").replace("Sintesi massima: ", "").replace("Sintesi: ", "")
    
    h1_match = h1_pat.search(content)
    h1_text = h1_match.group(1).strip() if h1_match else title
    
    # Try to find subtitle in header
    header_match = header_pat.search(content)
    subtitle = ""
    if header_match:
        header_content = header_match.group(1)
        # Find first p in header
        p_match = re.search(r'<p.*?>(.*?)</p>', header_content, re.IGNORECASE | re.DOTALL)
        if p_match:
            subtitle = p_match.group(1).strip()
            subtitle = re.sub(r'<[^>]+>', '', subtitle) # strip html tags
            
    main_match = main_pat.search(content)
    if not main_match:
        print(f"Error: <main> tag not found in {filename}")
        continue
        
    main_content = main_match.group(1).strip()
    
    # Generate ID
    lesson_id = filename.lower().replace(".html", "").replace(" ", "-").replace("à", "a").replace("è", "e").replace("ì", "i").replace("ò", "o").replace("ù", "u")
    lesson_id = re.sub(r'[^a-z0-9\-]', '', lesson_id)
    
    # Extract background/theme color class from header
    header_tag_match = re.search(r'<header class="([^"]+)"', content, re.IGNORECASE)
    theme_color = "slate"
    if header_tag_match:
        classes = header_tag_match.group(1)
        if "blue" in classes:
            theme_color = "blue"
        elif "amber" in classes:
            theme_color = "amber"
        elif "slate" in classes:
            theme_color = "slate"
        elif "stone" in classes:
            theme_color = "stone"
        elif "emerald" in classes:
            theme_color = "emerald"
        elif "purple" in classes:
            theme_color = "purple"
            
    lessons_data.append({
        "id": lesson_id,
        "title": h1_text,
        "subtitle": subtitle,
        "theme": theme_color,
        "htmlContent": main_content
    })

# Write to lessonsData.js
js_content = f"// Autogenerated by parse_lessons.py\nconst lessonsData = {json.dumps(lessons_data, indent=2, ensure_ascii=False)};\n"
with open("lessonsData.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Successfully parsed {len(lessons_data)} files into lessonsData.js")
